// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ehs-redesign/FreelancePortal.tsx": () => import("../components/mockups/ehs-redesign/FreelancePortal.tsx"),
  "./components/mockups/ehs-redesign/Linear.tsx": () => import("../components/mockups/ehs-redesign/Linear.tsx"),
  "./components/mockups/ehs-redesign/LinearV3.tsx": () => import("../components/mockups/ehs-redesign/LinearV3.tsx"),
  "./components/mockups/ehs-redesign/Stripe.tsx": () => import("../components/mockups/ehs-redesign/Stripe.tsx"),
  "./components/mockups/ehs-redesign/Vercel.tsx": () => import("../components/mockups/ehs-redesign/Vercel.tsx"),
  "./components/mockups/linear-recolor-aurora/LinearAurora.tsx": () => import("../components/mockups/linear-recolor-aurora/LinearAurora.tsx"),
  "./components/mockups/linear-recolor-cobalt/LinearCobalt.tsx": () => import("../components/mockups/linear-recolor-cobalt/LinearCobalt.tsx"),
  "./components/mockups/itinerary-day/Dark.tsx": () => import("../components/mockups/itinerary-day/Dark.tsx"),
  "./components/mockups/itinerary-day/Light.tsx": () => import("../components/mockups/itinerary-day/Light.tsx"),
  "./components/mockups/linear-recolor-ehs/LinearEHS.tsx": () => import("../components/mockups/linear-recolor-ehs/LinearEHS.tsx"),
  "./components/mockups/redesign-a-blueprint/FreelancePortal.tsx": () => import("../components/mockups/redesign-a-blueprint/FreelancePortal.tsx"),
  "./components/mockups/redesign-a-blueprint/ProductionTool.tsx": () => import("../components/mockups/redesign-a-blueprint/ProductionTool.tsx"),
  "./components/mockups/redesign-b-swiss/FreelancePortal.tsx": () => import("../components/mockups/redesign-b-swiss/FreelancePortal.tsx"),
  "./components/mockups/redesign-b-swiss/ProductionTool.tsx": () => import("../components/mockups/redesign-b-swiss/ProductionTool.tsx"),
  "./components/mockups/redesign-c-workshop/FreelancePortal.tsx": () => import("../components/mockups/redesign-c-workshop/FreelancePortal.tsx"),
  "./components/mockups/redesign-c-workshop/ProductionTool.tsx": () => import("../components/mockups/redesign-c-workshop/ProductionTool.tsx"),
  "./components/mockups/redesign-d-festival/CrewLogistics.tsx": () => import("../components/mockups/redesign-d-festival/CrewLogistics.tsx"),
  "./components/mockups/redesign-e-nativeos/CrewLogistics.tsx": () => import("../components/mockups/redesign-e-nativeos/CrewLogistics.tsx"),
  "./components/mockups/redesign-f-wayfinding/CrewLogistics.tsx": () => import("../components/mockups/redesign-f-wayfinding/CrewLogistics.tsx")
};
